Introduction

Sustainable cities and communities across the world are at risk due to rising sea levels and the threat it possesses. Across the planet, 190 million people are located on land predicted to be below high tide lines in the year 2100(1). This number does not include the number of locations at risk of flooding and other water-based natural disasters. This increase in high tide lines does not only threaten homes but also food supply and palatable water. Depending on the economic state of a nation, as well as its development, response to rising sea levels differ. Japan has had a long history of handling tsunamis, which have only increased in danger in recent years, has built thousands of kilometers in sea walls to limit the population from risks. Japan, in the modern era, is viewed as one of the most developed nations in the world. In line with this view would be Japan’s not only rapid response to ocean-based threats but also their preparation and reaction to them at the moment. When these forms of disasters occur people are alerted via a nationwide cellular update, a warning to get to high ground or shelter immediately in response to earthquakes that could cause Tsunami. Not only is the population response rapid but the amount of time given to the population is increased due to the towering sea walls slowing down these tsunamis. What followed the 2011 and 2014 major Tsunami was a plan for Japan to invest over $12 billion into maintenance, development, expansion, and building of sea walls across the nation(USE OLD SITE). Even this rapid response has its own handful of issues, obstructing access to the ocean, quality of life, etc. On the other hand, however, nations far less developed than Japan may not have the infrastructure capabilities to make such a definitive investment into its people. This is made even harder when the nation in question has its population separated by large masses of water such as in the Philippines. 
Since the 1950s the population of the Philippines has increased by over 80 million people(3). This rapid growth led to hasty industrial planning, poor placements of city developments, and a mass increase in farmland output. This output is strained today to keep up with producing enough food each year for the population it feeds. By looking at an example case within the Philippine’s current rising tides issue and pairing that with some data science methods to plan their future, predict their danger areas and prevent a mass dislocation scramble of their population. By employing existing agent-based models, digital elevation models (DEM), geographic information systems (GIS) paired with spatial statistics I hope to answer the question of whether or not large populations can be relocated sustainably without threatening current ways of life within urbanized areas. To answer this question I will start by evaluating the agent based-models. These are used to predict population response; in this instance, response to Tsunami allows one to understand which environments have the highest survivability rate and plan future cities to mimic those environments (4). The DEM calculates the depth/height of land. Over the years these methods have been enhanced by producing more reliable data that does not get distracted by foliage and other terrains. This method allows for a clear understanding of which areas are likely to see imminent flooding due to high tides changing as opposed to the occasional floods caused by tropical storms(1). And then lastly, employing GIS and spatial statistics as well as population projections one can understand and plan proactively for how introducing a new demographic into a “mega-urban environment” might impact the local infrastructure(5,6). 

## Inquiry Type
	The primary predicament with rising tides addressed in this paper will fall under urban planning which can be answered using an evaluative question. This particular inquiry allows for a base to be created from which sustainable urban planning can follow to prevent irreversible damages in the future. This planning will take into account future coastlines, communities that will need relocating as well as the threshold in which existing cities can handle their own growth with additional population injections from these displaced communities. By monitoring current communities in high tide regions, for example, the island of  Ubay, one can understand the rationale behind the community’s reluctance to relocate, even with the assistance of the government(7). Using the two models along with the geospatial data and population projections gives a rather robust base to begin a sustainable urban development plan. An issue, such as rising tides, is rather black and white on the surface. Predicting what populations are at risk becomes a simple evaluation of current data on the height of regions above sea level. The difficulty in taking measures against such an issue arises in the timing. In the world’s current state high tide level growth rates have increased and are predicted to be just under 2m higher by the end of the century (2).  This takes into account rising levels of carbon emissions(low, medium, and high output) up until the end of the century. The rate at which carbon emissions change has a direct impact on the state of the ice levels in the arctic. When all this is taken into account there is a 5% chance of over a 2m rise in high tide lines by the turn of the century. With rising high tide lines, there will be adjustments with coastal lines. Depending on the makeup of the coast, coastal erosion may be expedited, rivers will spill over constantly while expanding and more people will be forced to make a choice of living life in high risk flood areas or attempting to start life anew in the city. The population demographics, accounting for language, ethnicity, and religion amongst other covariates, will play a major role in the decision making of those in small communities attempting to relocate. How the government responds to these covariates can lead to them understanding how to incentivise moving. In turn there will be complete guaranteed safety. This relies heavily on the actions of the government as well as the overall trust people have in said government. Some variables that will briefly be acknowledged throughout will be sustainable development of cities, from water potability, food resource sufficiency, and healthy population growth within the confines of future coastlines.  

## Methods
	
### Digital Elevation Models 
	Digital elevation models are created from a conglomeration of other datasets to produce accurate geographical models incorporating terrain, depth and consistency. Often these models have two versions, a DTM that is considered the bare earth model and the DSM, which considers vegetation and buildings in the mapping(8). The main focus for this inquiry will be DTM for the purpose of understanding at risk areas of flooding as well. When paired with DSM this can be very effective at understanding at risk locations with buildings and populations. This can play into future urban planning and understanding as well to acknowledge certain areas near cities as inhospitable for informal settlements to form as well. In this particular DEM a new base data set is being evaluated and compared to an older base data set to see if the newer one will provide a more accurate picture for global mapping. With the advancement of more accurate DEM’s monitoring, constantly changing coastlines will become easier and more efficient and not require constant validating of the data. The changes in coastlines in the coming years requires a more robust and reliable system which can allow for effective urban planning in the future. The importance of the DTM becomes evident in a model produced by 


### Population Projections and Geographic Information Systems
	The population projections for a nation have alway been pivotal in understanding the nation's ability to develop in different aspects of functionality. These projections are calculated through estimating improvements in: healthcare, food supply, potable water, amongst other covariates. Understanding one’s population projections allows for proper inclusive economic growth, urban planning and general sustainable development. Particularly in cities under development the importance in the sustainable growth of these environments is pivotal upon the way this data is utilized by the government. Are certain ethnicities ostracized within cities, relegated to the outskirts or living in informal settlements. In relation to the main question, are these informal settlements sustainable in the development of these cities or will other forms of affordable need to be supplied. Informal settlements being taken over to build new affordable housing lose their importance when the settlement and its dwellers choose to relocate their settlement instead of making use of the government sponsored developed housing. These new settlements may be under threat of new high tide lines, a very realistic threat. 
	In regards to population projections there are varying degrees of detail. 

                                        Pc,t = Pc,t−1 + Bc,t − Dc,t + Mc,t, 

